from utils.error import CustomException


class DaemonError(CustomException):
    """Exception raised for errors in the Daemon class."""

    pass
