from utils.error import CustomException


class TriggerError(CustomException):
    """Exception raised for errors in the Trigger class."""

    pass
